spring.application.name=springbootweb
spring.datasource.url=jdbc:h2:file:C:/Users/ar334/Desktop/Springboot/springbootweb/DB
spring.datasource.username=aceDB
spring.datasource.password=8920
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update